# APS-LAB

CREATE TABLE Class (`id` INT PRIMARY KEY AUTO_INCREMENT,  `name` VARCHAR(50));
INSERT INTO Class (`name`) VALUES ("Anandhu"), ("Swathy"), ("Shijin");

SELECT * FROM Class;


DELETE FROM Class WHERE id = 2;
ROLLBACK;
SELECT * FROM Class;


DELETE FROM Class  WHERE id = 2;
COMMIT;

SELECT * FROM Class;

START TRANSACTION;
SAVEPOINT SP1;

DELETE FROM Class WHERE id=1;

SAVEPOINT SP2;

DELETE FROM Class WHERE id=3;

ROLLBACK TO SP1;
COMMIT;
SELECT * FROM Class;
